### ISSUE TITLE
Error with couchbase_manage_buckets: true and Ansible v2.2.1.0

### ISSUE THREAD

**Issue by pred2k** [mrlesmithjr/ansible-couchbase#1]
Hi, i want to create couchbase buckets with this role and defined the variables:

    - role: roles/mrlesmithjr.couchbase
      couchbase_version: '4.5.0'
      couchbase_manage_buckets: true
      couchbase_buckets:
        - name: mybucket
          ram_size: 512
          state: present

 During the run it fails with this output:

TASK [../../ansible-couchbase : manage_buckets | listing current buckets] ******
changed: [localhost]

TASK [../../ansible-couchbase : manage_buckets | creating buckets] *************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'item.name not in couchbase_bucket_list.stdout and item.state == \"present\"\n' failed. The error was: error while evaluating conditional (item.name not in couchbase_bucket_list.stdout and item.state == \"present\"\n): Unable to look up a name or access an attribute in template string ({% if item.name not in couchbase_bucket_list.stdout and item.state == \"present\"\n %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': coercing to Unicode: need string or buffer, StrictUndefined found\n\nThe error appears to have been in '/tmp/roles/ansible-couchbase/tasks/manage_buckets.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: manage_buckets | creating buckets\n  ^ here\n"}

i tried to debug it, but could'n discover the problem.

**Comment by mrlesmithjr** [comment]
@pred2k Can you tell me which Linux Distro and version you are using? I will do some testing.

**Comment by mrlesmithjr** [comment]
@pred2k Issue should be resolved now.

**Comment by pred2k** [comment]
@mrlesmithjr Distro was Ubuntu trusty. Thank you very much for fixing. What was the problem? Quoting of the variable at with_items: ?

**Comment by mrlesmithjr** [comment]
@pred2k No worries at all. Yeah, it was the with_items quotation.
